### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by stephanepericat**
Done as discussed.

### CODE REVIEW

**Comment by dragoverde** [comment]
1) pom.xml - fix indentation
2) all local widget/container readme files should have the "Additional resources" section listing all additional resources: in this case it's import xml
3) root readme file should include steps 1-3 from usage.txt in the "Configuration" section

**Comment by stephanepericat** [comment]
fixed

**Comment by igord** [comment]
Stephan, here is the documentation of REST library:
https://github.com/Backbase/mosaic-rest-js
bb rest is just a command line interface of that library

Regarding the bb property tool, here is what is happening when you run:
bb property --prop

1. look for xml file in cwd expecting standard catalog item file
2. parse a name from xml file and create REST API request to the backend to
retrieve current properties
3. compare properties in xml with properties on server. if something is
missing in xml, it will add markForDeletion
4. submit xml file via REST API to the server

So with one command, your properties are submitted, updated or removed.
What you also need to define is portal settings. By default localhost:777
with user admin/admin is used.
If you want to change that, create .bbrc configuration file in your folder.
it is json file like this one:

{
  "username": "john",
  "password": "HU&69wev*!$8",
  "portal": "myportal"
}

**Comment by dragoverde** [comment]
All good

**Pull request merged**
